### ISSUE TITLE
update voila-embed to support voila 0.2

### ISSUE THREAD

**Issue by havok2063** [mariobuikhuizen/voila-embed#14]
Now that `jdaviz` supports voila>0.2, can we update the `voila-embed` and `voila-embed-vuetify` packages to support voila>=0.2?

**Comment by mariobuikhuizen** [comment]
Support added in 452d2241fbd1377de49e5ca07c9c249f74455378, which I forgot to push. There are no changes needed to voila-embed-vuetify.

**Comment by havok2063** [comment]
Great! Thanks!
