### ISSUE TITLE
styling issues for bqplot with web embed

### ISSUE THREAD

**Issue by havok2063** [mariobuikhuizen/voila-embed#15]
This issue is a reprise of https://github.com/mariobuikhuizen/voila-embed/issues/6.  I'm using `bqplot=0.12.21`.  Is there a correct `bqplot` version I should pin to, to see the proper styling?

**Comment by maartenbreddels** [comment]
I have trouble reproducing it, which voila version are you using?

**Comment by havok2063** [comment]
Hmm.  I'm using `voila=0.2.6`.

**Comment by maartenbreddels** [comment]
Yes, got it! I think I know how to fix it.
