### ISSUE TITLE
voila-embed broken with voila 0.2.8

### ISSUE THREAD

**Issue by havok2063** [mariobuikhuizen/voila-embed#18]
Looks like the latest voila breaks voila-embed.  `voila=0.2.7` works but after updating to `0.2.8` we now get the following error in the console when attempting an embed:
```
VM17:1 GET http://localhost:17000/api/kernels/3654334f-6973-4d8e-b946-bb78934eb99d?1618319289845 404 (Not Found)
voila.js:455 Uncaught (in promise) TypeError: Cannot read property 'kernelChanged' of undefined
    at new so (voila.js:455)
    at new Ys (voila.js:469)
    at getWidgetManager (voila-embed.js:103)
    at voila-embed.js:142
```

**Comment by maartenbreddels** [comment]
@mariobuikhuizen this also happens when we use the old voila-vuetify template, or an old jdaviz release right? Maybe that will help debug it.

**Comment by havok2063** [comment]
There is a similar error popping up here, https://github.com/spacetelescope/jdaviz/issues/552, but unrelated to `voila-embed`, related to running jdaviz in a pure voila desktop app mode.  They've seen a similar console error in voila `0.2.7` and `0.2.9`.
