### ISSUE TITLE
Voila Creating Directories with Socket Files in Temp Folder and Not Deleting Afterward

### ISSUE THREAD

**Issue by sachin-smart** [mariobuikhuizen/voila-embed#25]
Hello,

Thank you for creating and maintaining Voila, which is an extremely useful tool for me.

Recently, I found that my PC (Windows 10) was being slowed down by millions of folders that were created in the Temp folder on the local drive. In each of these millions of folders, there is a 0 byte socket file. The titles of the directories generally begin with 4 characters, the first of which is usually "u", followed by "." and then one or two characters that follow a sequence: single digits, then the alphabet, then single digits and alphabet for the second character and "1" for the first character, and so on.

After lots of testing out different applications and trying to track down what was creating these directories, I found that whenever I launched voila (or even if I launched jupyter in conda environments with the voila extension), these directories were created. Sometimes, the creation of the directories would be continual and only stop once the Command Prompt was terminated. The curious part is that these folders and the files in them are/were not being cleared. Please could you help resolve this issue so I can continue to use Voila?

Thanks!

This one with Voila extension creates the directories in Temp and does not clear them.
![Jupyter Lab with Voila Extension in conda environment](https://user-images.githubusercontent.com/61995745/138092208-1fb00402-a844-471f-9942-217501660b1f.PNG)

This version does not.
![Jupyter Lab without Voila Extension](https://user-images.githubusercontent.com/61995745/138092211-6a1ec7ba-f45a-4bff-943d-6925d681fc72.PNG)

Here are some examples of the directories mentioned.
![Directories in Temp Seemingly Created By Voila](https://user-images.githubusercontent.com/61995745/138092676-20642552-4656-49c5-8413-897f33a8e26f.PNG)

**Comment by mariobuikhuizen** [comment]
I think you meant to open an issue on https://github.com/voila-dashboards/voila instead of on this repository (voila-embed)

**Comment by sachin-smart** [comment]
Yes, I did. Apologies and thanks for pointing that out!
