### ISSUE TITLE
styling issues with updated bqplot version

### ISSUE THREAD

**Issue by havok2063** [mariobuikhuizen/voila-embed#6]
It seems `bqplot==0.12.3` creates an incorrect styling when rendering plots on the web, compared to `bqplot==0.11.9`.  The latest `bqplot` renders correctly inside notebooks, but renders incorrectly when embedded on the web.  See attached image.  The `0.11` version renders correctly both in notebooks and the web.    

I need to render FITS image data with `bqplot-image-gl`, which only works with `bqplot>=0.12`, so ideally I'd like to update bqplot.  Is there a reason `voila-embed` is pinned to use `bqplot=0.11`?   Alternatively, is there a different `bqplot`-related package other that `bqplot-image-gl` that lets me render FITS image data within the framework of bqplot?

<img width="1301" alt="Screen Shot 2020-02-05 at 10 11 36 AM" src="https://user-images.githubusercontent.com/1836302/73855586-47cd6900-4802-11ea-86c2-23bf09e984f2.png">

**Comment by mariobuikhuizen** [comment]
Thanks for reporting this issue.

We've pinned bqplot to 0.11 because 0.12 contained a visual bug which affected voila-vuetify at the time. This has since been resolved.

With commit d14c1c6 you can now use bqplot>=0.12.

I'm no expert in using plot libraries, so I can't advise you on alternatives to bqplot.

**Comment by havok2063** [comment]
Great, thanks for the fix Mario.  

Oh I didn't mean alternatives to `bqplot`.  I mean alternate ways within `bqplot` to display FITS images, other than `bqplot-image-gl`.  It seems that `bqplot-image-gl` is a non-affiliated package and not really maintained / updated.  Is there a plan to merge `bqplot-image-gl` into the core `bqplot` and expand its functionality?

**Comment by maartenbreddels** [comment]
> bqplot-image-gl

We (@astrofrog and me) kept it out of bqplot so we could put astronomy specific parts in it, which would not make sense to put in bqplot. It is maintained actually, just not very active :)

**Comment by havok2063** [comment]
That makes sense.  Thank Maarten!
